# Cloudflare Pages configuration
name = "dci-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Enable Node.js compatibility for the Edge Runtime
[build]
command = ""

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
